### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by gumbarros** [riccardoFasan/stack-overflow-tweaks-tool#1]
First things first, congratulations for the tool. I use it everyday.
I caught a error.
Firefox text is being copied HTML encoded.
![image](https://user-images.githubusercontent.com/52143624/197905258-7a7051ba-0c60-4d73-a1d2-91bb8cc03109.png)

![image](https://user-images.githubusercontent.com/52143624/197905225-0d4b7e86-0cd4-4754-85b6-361cf8823e6e.png)
Where is the firefox-branch so I can submit a PR with a fix?

**Comment by gumbarros** [comment]
@riccardoFasan

**Comment by riccardoFasan** [comment]
Hi @gumbarros , sorry for being late, GitHub didn't send me any notification.

I'm very glad that the tool is useful and I'm even more glad you want to submit a PR 🤩.

I removed the Firefox branch and created a script that builds the extension automatically, applying the differences between Chromium-based browsers and Firefox.
Just run `npm run build <target_browser>` to use it (target_browser can be `firefox` or `chromium`).

So you can start your PR directly from develop.

**Comment by gumbarros** [comment]
> Hi @gumbarros , sorry for being late, GitHub didn't send me any notification.
> 
> I'm very glad that the tool is useful and I'm even more glad you want to submit a PR 🤩.
> 
> I removed the Firefox branch and created a script that builds the extension automatically, applying the differences between Chromium-based browsers and Firefox.
> Just run `npm run build <target_browser>` to use it (target_browser can be `firefox` or `chromium`).
> 
> So you can start your PR directly from develop.
> 

Thanks for the response 😁, when I have some spare time I will develop the fix.

**Comment by gumbarros** [comment]
@riccardoFasan Is there a motiviation to use this method? This is what causing my copied text to be weird.

Example:

Before copying
```
<h1>A answer I want to copy</h1>
```
After copying
 ```
&lt;h1&gt;A answer I want to copy</h1>
```
```js
function getPlainText(html) {
	//stackoverflow.com//questions/15180173/convert-html-to-plain-text-in-js-without-browser-environment#answer-20071776
	html = html.replace(/<style([\s\S]*?)<\/style>/gi, '');
	html = html.replace(/<script([\s\S]*?)<\/script>/gi, '');
	html = html.replace(/<\/div>/gi, '\n');
	html = html.replace(/<\/li>/gi, '\n');
	html = html.replace(/<li>/gi, '  *  ');
	html = html.replace(/<\/ul>/gi, '\n');
	html = html.replace(/<\/p>/gi, '\n');
	html = html.replace(/<br\s*[\/]?>/gi, '\n');
	html = html.replace(/<[^>]+>/gi, '');
	return html;
}

```
