### ISSUE TITLE
Settings refresh after closing browser

### ISSUE THREAD

**Issue by amadeusjustinn** [riccardoFasan/stack-overflow-tweaks-tool#7]
**A quick summary and/or background**
The settings turn off after the browser is closed and reopened, e.g. after a Firefox update.

**Steps to reproduce**
Turn any set of settings on, close the browser, then open the browser again.

**What you expected would happen**
The settings are preserved before and after reopening.

**What actually happens**
Every setting is turned off.

**Comment by riccardoFasan** [comment]
Got it, I'm working on it👍

**Comment by gumbarros** [comment]
When the extension is updated, the settings are also cleared because of this snippet:
```js
chrome.runtime.onInstalled.addListener(() => {
  chrome.storage.sync.set({ jumpToTheAnswer: false });
  chrome.storage.sync.set({ jumpToTheMostVoted: false });
  chrome.storage.sync.set({ highlightAnswer: false });
  chrome.storage.sync.set({ getAnswersLink: false });
  chrome.storage.sync.set({ copyCode: false });
  chrome.storage.sync.set({ hideNavBar: false });
  chrome.storage.sync.set({ hideTooltipsBar: false });
});
```

**Comment by amadeusjustinn** [comment]
Thank you @riccardoFasan and @gumbarros for the quick response time! Truly appreciate it!
